### ISSUE TITLE
Gender question resulted in [object Object] as answer field

### ISSUE THREAD

**Issue by moduloprime** [GoogleChrome/experience-sampling#231] opened 2015-04-29 20:52 UTC
Has something to do with checkbox question and Other field and checking multiple things, but I don't have exact repro steps

**Comment by adrifelt** [comment] 2015-05-05 01:28
I tested this every way I can think of, and I can't reproduce it. My best guess is that it was fixed by one of us incidentally when we made the recent changes to how checkboxes are recorded.

**Closed by adrifelt** 2015-05-05 01:28 UTC
Labels: technical bug
